name = "Baie"
description = "A grounded theme for Zola"
tags = []
license = "MIT"
homepage = "https://github.com/Wtoll/Baie"
min_version = "0.4.0"
demo = "https://wtoll.github.io/baie"

[extra]

[author]
name = "Will Toll"
homepage = "https://wtoll.com/"
